Fix missing "__off_t" on NetBSD 10
NetBSD uses a type redefinition guard for off_t[1] with the same name,
confusing bindgen and making it generate a reference to a missing type:

```
error[E0412]: cannot find type `__off_t` in this scope
     --> .../target/debug/build/openssl-sys-f09155f99ab31e50/out/bindgen.rs:24508:17
      |
24508 |         offset: __off_t,
      |                 ^^^^^^^ help: a type alias with a similar name exists: `off_t`
```

[1]: https://github.com/NetBSD/src/blob/9ae2aa18e3f4ffeb1efda2bdd171a1f6d22fc3ce/sys/sys/types.h#L191